library(shiny)
library(ggplot2)
library(leaflet)
library(raster)
library(dygraphs)
library(plyr)
library(xts)
library(zoo)
library(stringr)
library(lubridate)
library(markdown)
library(DT)

vardescr <- read.table("vardescr.txt", sep="\t", stringsAsFactors = F)
tamp_retailers <- read.csv("tamp_retailers.csv", stringsAsFactors = FALSE, header=T)

shinyUI(fluidPage(

fluidRow(
column(12,
# HEADER
h1("Data stories from loading bays"),
h3("UNDER CONSTRUCTION!"),
br(),
tabsetPanel(


############################################################################################################
## Tab1: HOME
tabPanel("Home",
br(),
fluidRow(
column(12,
navlistPanel(well=T, widths = c(3, 9),
         
tabPanel("Welcome!", ###
         
  #p("Hi! This website is the result of the first phase of the", strong("Large urban freight traffic
  #  generators (LFGs) project"), "- to collect 
  #  and visualise data from several LFGs. This is is part of a
  #  larger effort to better understand and characterize the freight-generated traffic in
  #  metropolitan areas using both empirical and theoretical tools."),

  #p("The aim of this interface is 
  #  to understand the “size” and main features of the goods vehicles traffic generated by 
  #  large establishments. In doing so, we hope to identify the main issues that arise at these buildings, 
  #  and to drive us to the next phase of the project, namely to identify which solutions could potentially 
  #  tackle these issues and to provide a data-driven ex-ante impact assessment of these policies."),
                  
  #p("We have currently focused on large commercial centres (shopping malls), situated in the city of 
  #  Singapore. We hope in future development of the project to include different kinds of buildings 
  #  such as hospitals and schools. We further focused on goods vehicles traffic and not on the passenger traffic.")
  
  p("This website is the result of the IDA - SUTD collaboration in an effort to understand freight-generated traffic in metropolitan areas and 
    explore the concepts of", 
  strong("in-mall goods distribution system"), 
  "and", 
  strong("Urban Consolidation Centre"),
  "in Singapore."),
  
  p("The concept of in-mall goods distribution system consists in the creation of a central goods receiving station in a retail mall, 
  receiving and consolidating goods deliveries to retailers within the mall. In the absence of a centralised receiving station, 
  each carrier have to independently walk to the store with the deliveries. An in-mall distribution system is expected to reduce handling 
  time and congestion at loading bays. An Urban Consolidation Centre (UCC) have the same function of a central receiving station as in 
  the in-mall distribution, with the difference that the central receiving station is placed in a different location than the one of the 
  mall, hence further reducing the number of arrival trucks at the mall, tackling congestion at the mall and in its premises."),
  
  p("The aim of this interface is to provide:"),
  
  tags$ul(
    tags$li("Meaningful data to support the planning of urban freight systems."),
    tags$li("Better understanding of In-Mall distribution."),
    tags$li("Insights on the current challenges for an effective In-Mall distribution system.")
  ),
  
  p("The project is currently on data analysis phase. System modelling and design recommendations will be included in later stages.")

    ),#END of tabPanel "welcome"






tabPanel("Objectives", ####################################
  h3("Objectives"),
  p("The primary question we would like to answer is: what is the current state of the system? Where by 'system' we mean
    the bundle of processes involved before, during and after a goods vehicle has delivered, picked-up goods or performed some
    form of service at a large retail estalbishment. Such processes usually start with the cruising for parking and parking of the vehicle,
    then followed by the 'handling operations' (loading, unloading of goods deliverying inside the mall, picking-up goods or performing a service).
    Such processes are fundamental for the realization of the logistics process, of the very last meters of a delivery. These very last meters
    are often the most 'inefficient' distance covered by the logistics process, where several inefficiencies arise due to congestion of
     freight vehicles, long handling times, lack of resources and space for performing loading and unloading, as well as generating
    several externalities to the neighbourhood and among tranport operators."),
  h3("Phases"),
  p(strong("1. Data collections:"),"Collect data at large retail establishments and commercial urban areas."),
  p(strong("2. Data analysis:"), "Identify and quantify potential externalities and economic inefficiencies caused by freight traffic at large 
    retail establishments."),
  p(strong("3. Modeling:"), "Model the processes involved in the parking and handling operations at large etablishments. Identify suitable 
    urban logistics initiatives which can possibly tackle the externalities identified and simulate their effects using the identified 
    methodology.")
 ),#END of tabPanel LFG project

 
tabPanel("Data description", ################################################
         
         h3("Data sources"),
         p("In the data collected a single observation is a 'truck-shipment' entering the premises of a shopping mall. 
           A 'truck-shipment' unit consists in a goods vehicle carrying one driver and sometimes one or more helpers, delivering 
           one or more shipments to its customers (i.e. store(s) located inside a shopping mall)."),
         p("Each observational unit, uniquely identified by the licence plate, is followed from the time it enters the system, i.e. the
           premises of a mall, to the time it leaves the system. In between, we have tracked all possible observable processes
           performed by the goods vehicle and its driver and helpers, in driving, parking, performing the delivery or some other form of services 
           for the customers."),
         p("For each observed unit we measured several variables, which we distinguish into four types: delivery, vehicle, driver and traffic variables.",
           strong("Delivery variables"), "describe a single shipment of a truck-shipment unit, such as size, types of goods delivered and store the goods are delivered to.", 
           strong("Vehicle variables"), "describe the goods vehicle used, such as car maker, vehicle size and loading factor.", 
           strong("Driver variables"), "are collected directly via drivers surveys and describe the drivers' routing choices and parking behaviours. 
           Finally,",
           strong("traffic variables"), "measure the freight traffic level at the premises of the establishment."),
         p("The aim of the current research effort is to integrate the above mentioned sources of data regarding all the goods vehicles 
           arriving at the selected shopping malls, in order to assess the current state of the system, quantify potential expernalities 
           generated and understand how logistics initiatives can impact the system."),
         br(),
         
         tabsetPanel(
           tabPanel("Delivery variables", ###
                    br(),
                    p("Truck drivers and helpers, after having parked the goods vehicle, start a", 
                      strong("handling process"),
                      ". Handling consists in performing one or more",
                      strong("deliveries"), 
                      ". Each delivery consists in carrying a certain amount of goods from the location where the vehicle parked 
                      to the receiver or receivers' locations. We have collected several variables describing single deliveries,
                      some have been collected by observing the handling process, others have been obtained interviewing the driver."),
                    p("Note: a goods vehicle that parked in the premises of an establishment does not necessarily perform a delivery. Some
                      vehicles might instead pick-up goods or perform some form of service (maintenance, garbage collection, 
                      vehicles carrying people etc.). We have collected data on these vehicles as well, although no actual delivery is performed."),
                    wellPanel(
                      fluidRow(
                        column(3,
                               br(),
                               strong("Variable name:") 
                        ),
                        column(9,
                               selectInput("delivery_var", " ", 
                                           choices = vardescr[vardescr[,1]=="delivery",2]
                               )
                        )
                      ),
                      fluidRow(
                        column(3,
                               strong("Observations:")   
                        ),
                        column(9,
                               textOutput("nrows_delivery_var")
                        )
                      ),
                      br(),
                      fluidRow(
                        column(3,
                               strong("Description:")   
                        ),
                        column(9,
                               textOutput("descr_delivery_var")
                        )
                      )
                    ) #END of wellpanel
                    ), #END of delivery tabpanel
           
           tabPanel("Vehicle variables", ##
                    br(),
                    p("Direct observation of the goods vehicles can give us a lot of information regarding: the amount of
                      pollution it generates, which company owns it and which company operates it (not necessarily the same).
                      We have collected data on the type of the vehicle and the model, whether it is refrigerated, any logo
                      or branding displayed. We have observed the loading factor (how 'full' is the truck) as well
                      as counted the number of workers operating it. Finally, we use the car plate of a vehicle as a unique identifier, although
                      they are not reported in the study for privacy concerns. Further, the information regarding
                      the side plate has been used to extract other information (origin of the vehicle trip, type of company
                      operating the vehicle etc.), while the original name of the company as written in the side plate will not
                      be used."),
                    wellPanel(
                      fluidRow(
                        column(3,
                               br(),
                               strong("Variable name:") 
                        ),
                        column(9,
                               selectInput("vehicle_var", " ", 
                                           choices = vardescr[vardescr[,1]=="vehicle",2]
                               )
                        )
                      ),
                      fluidRow(
                        column(3,
                               strong("Observations:")   
                        ),
                        column(9,
                               textOutput("nrows_vehicle_var")
                        )
                      ),
                      br(),
                      fluidRow(
                        column(3,
                               strong("Description:")   
                        ),
                        column(9,
                               textOutput("descr_vehicle_var")
                        )
                      )
                    ) #END of wellpanel
                    ), #END of vehicle tabpanel
           
           tabPanel("Driver variables", ##
                    br(),
                    p("The agents that perform the delivery, pickup or service are usually the drivers of the goods vehicles or the helpers.
                      These agents often are responsible for taking operational decisions regarding the deliveries such as, routing, priorities,
                      time of delivery as well as are those who might decide to abandon the queue, to park on the street, or to leave the area
                      and come back later on."),
                    p("Only through driver surveys we can obtain information regarding the origin and destination of the goods, the utilization
                      of the vehicle (loading, number of stops in a day etc.), the business model behind the logistics operations we are observing
                      as well as obtaining behavioural insights regarding the parking and driving behaviours."),
                    wellPanel(
                      fluidRow(
                        column(3,
                               br(),
                               strong("Variable name:")
                        ),
                        column(9,
                               selectInput("driver_var", " ", 
                                           choices = vardescr[vardescr[,1]=="driver",2]
                               )  
                        )
                      ),
                      br(),
                      fluidRow(
                        column(3,
                               strong("Observations:")   
                        ),
                        column(9,
                               textOutput("nrows_driver_var")  
                        )
                      ),
                      br(),
                      fluidRow(
                        column(3,
                               strong("Description:")   
                        ),
                        column(9,
                               textOutput("descr_driver_var")
                        )
                      )
                    ) # END of wellpanel     
                    ),#END of drivers tabpanel
           
           tabPanel("Traffic variables", ##
                    br(),
                    p("Traffic variables aim at capturing the movement of the goods vehicles while it is not parked. From the time
                      it enters the system (i.e. the premises of the mall) to the time it starts the handling operations (loading, unloading or
                      performing some form of service). Most of these variables have been captured with cameras and thereafter processed
                      to extract information such as time of arrival and exit, total dwelling time (the difference between the previous two variables),
                      queueing time (time spent waiting in queue to get into the loading bay) and other variables.") ,
                    
                    wellPanel(
                      fluidRow(
                        column(3,
                               br(),
                               strong("Variable name:")
                        ),
                        column(9,
                               selectInput("traffic_var", " ", 
                                           choices = vardescr[vardescr[,1]=="traffic",2]
                               )  
                        )
                      ),
                      br(),
                      fluidRow(
                        column(3,
                               strong("Observations:")   
                        ),
                        column(9,
                               textOutput("nrows_traffic_var")   
                        )
                      ),
                      br(),
                      fluidRow(
                        column(3,
                               strong("Description:")   
                        ),
                        column(9,
                               textOutput("descr_traffic_var")
                        )
                      )
                    ) # END of wellpanel
                    ),#END of traffic tabpanel 
           
           tabPanel("All variables", ###
                    br(),
                    wellPanel(
                      fluidRow(
                        column(3,
                               br(),
                               strong("Variable name:") 
                        ),
                        column(9,
                               selectInput("all_var", " ", 
                                           choices = vardescr[,2]
                               )
                        )
                      ),
                      fluidRow(
                        column(3,
                               strong("Observations:")   
                        ),
                        column(9,
                               textOutput("nrows_all_var")
                        )
                      ),
                      br(),
                      fluidRow(
                        column(3,
                               strong("Description:")   
                        ),
                        column(9,
                               textOutput("descr_all_var")
                        )
                      )
                    ) #END of wellpanel
           ) #END of "all variables" tabpanel
           ) #END of TabsetPanel
         
         ),#END of tabPanel Freight data



        
tabPanel("Authors", ##########################################
         h3("Singapore University of Technology and Design (SUTD) Research Team"),
         tags$ul(  
           tags$li("Lynette Cheah, Professor (PI)."),
           tags$li("Ngai-Man Cheung, Professor."),
           tags$li("Costas Courcoubetis, Professor."),
           tags$li("Laura Guerrero, Research Fellow."),
           tags$li(a("Giacomo Dalla Chiara, Ph.D. candidate.", href="http://esd.sutd.edu.sg/phd-students/giacomo-dalla-chiara/"))
         )
  )#END of tabPanel Authors


)
)#END of column
)#END of fluidRow
),#END of tabPanel "Home"









############################################################################################################
## Tab 2: Large Urban Traffic Generators
tabPanel("Large Urban Traffic Generators",
br(),
fluidRow(
  column(3,
    wellPanel(
      selectInput("malls_map_visual", "Choose visualization:", 
                  choices=c("Location"="loc_only",
                            "Number of stores"="no_stores",
                            "Stores per squared m."="store_density")
                  )
      #"here hist",
      #"here plot"
      ), #END of wellPanel
    
    wellPanel(
      h5("Total number of malls considered:"),
      textOutput("tot_malls"),
      br(),
      h5("Estimated total truck-trips generated per day:"),
      textOutput("trips")
      )
    ),
  column(9,
    leafletOutput("map_malls")
    )
  )
), #END of TabPanel on malls map






############################################################################################################
## Tab 3: DATA SUMMARIES
tabPanel("Case studies summaries",
br(),
fluidRow( #first row
  
  column(6,
    leafletOutput("mymap")
         ), #END column with map
  
  column(6,
      conditionalPanel(
            condition = "!output.data_collection_location",
            br(),
           br(),
           br(),
            br(),
            br(),
            br(),
            br(),
            h3("Click on the map to visualize the data summary")
            ),
      conditionalPanel(
        condition = "output.clickme == 'tamp'",
        br(),
        imageOutput("tamp_map")
        ),
      conditionalPanel(
        condition = "output.clickme == 'north'",
        br(),
        imageOutput("northp_map")
        )
      ) #END column with pic of location
),#END of first row with maps

fluidRow( #second row

  
  
  
  
#----------------------------      TAMPINES

conditionalPanel(condition = "output.clickme == 'tamp'",
    h2("Mall2 case study"),
    tabsetPanel(
      tabPanel("Overview",
        br(),
        column(8,
          HTML(markdownToHTML(fragment.only=TRUE, text=c("
#### Data collection activity
The data collection activity at Mall2 took place on the weekdays **<span style='color:red'>Thursday 21st and Friday 22nd January 2016</span>**, each day 
for 10 hours: **<span style='color:red'>6 am - 6 pm</span>**. A total of 17 surveyors were employed over two days and four video cameras. Surveyors duties were to interview
the driver, perform vehicle observations and operate the video cameras. The cameras were collecting data on the traffic outside the mall.
On the second day one of the two exit cameras was moved from the road-side to the entrance of the loading bay (level B2), to capture license plate and time stamp of all the vehicles entering the loading bay.

#### Overview of data collected
NA

#### Site description
* **Mall2**: The Mall2 is located in the eastern part of Singapore. In the vicinity of the mall there is an MRT station, a Bus Interchange and
two other large shopping malls.

   There are a total of 162 stores, distributed over 5 floors overground (levels 01-05) and one floor underground (level B1). The total retail
floor area is of 29233.7 square meters.Among the anchor tenants there are Isetan, NTUC Fairprice and POPULAR bookstore.
                                                        
* **Service road**: Goods and passenger vehicles can access the mall from a 200 meters-long one-way three-lanes service road,
on the sides of which **<span style='color:red'>four cameras</span>** were deployed, two at the beginning of the road, two at the exit.
The road section analysed contains two traffic lights, each with 30 seconds of red clearance. 
                                                        
* **Passenger car-park**: The passenger carpark is accessible from both the north-east and the north-west sides of the mall. 
The north-west entrance to the passenger carpark is shared with the entrance to the loading bay. The carpark exit is 
on the north-west side of the mall.Each vehicle entering the carpark have to pay SG$ 1.07 for the first hour and SG$ 0.15 for every
subsequent 15 minutes. 
                                                        
* **Loading bay**: The loading bay is located at the level B1 of the mall and is accessible from the north-west side 
of the mall through a two-lanes two-way slope. It can hosts up to **<span style='color:red'>16 goods vehicles</span>**. 
Access to the LB is regulated by a barrier which opens only when there are lots available. 
The loading bay is open from 6am to midnight and it **<span style='color:red'>costs SG$ 1 per 30 minutes</span>** or part thereof.
The stores can be accessed from the loading bay via a service lift.

* **Queue formation**: The queue for accessing the loading bay starts forming at the barrier inside the loading bay, and spill over the 
service road after XXX vehicles are in queue. **<span style='color:red'>The queue is visible from the service road only when there are at least 
 XXX vehicles in queue</span>**.

* **Street parking**: Illegal parking on the service road was occasionally observed 
along the sides of the road as shown in the above map (green areas), for a total of approximately XXX goods vehicles simultaneously.
")))
),
    column(4,
        br(),
        imageOutput("tamp_overview")
        )  

    ), # END of overview

  tabPanel("Vehicle count",
      fluidRow(
        br(),
        column(3,
          wellPanel(
            radioButtons("tamp_vehicle_count_visual", "Choose type of visualization:", 
                  choices = c("Table","Percentage", "Barplot")),
            selectInput("tamp_vehicle_split", "Split by:", 
                   choices=c("none",
                             "Interviewed vs non-interviewed", 
                             "Vehicle type", 
                             "Refrigerated vs. non-rerigerated",
                             "Parking location",
                             "Number of workers"))
            )    
          ),
        column(9,
          "main panel",
          DT::dataTableOutput("tamp_vehicle_table")
          )
        ) #END of fluidrow
      ), # END of vehicle count

  tabPanel("Delivery count",
      "..."
      )
  ) #END of tabsetpanel

), ### END OF TAMPINES conditionalpanel





#-------------------      NORTHPOINT

conditionalPanel(condition = "output.clickme == 'north'",
h2("Mall1 case study"),
tabsetPanel(
    
tabPanel("Overview",
  br(),
  column(8,
  HTML(markdownToHTML(fragment.only=TRUE, text=c("
#### Data collection description
The data collection activity at Northopint mall took place on the weekdays **<span style='color:red'>Wednesday 24th, Thursday 25th 
and Firday 26th June 2015</span>**, starting from 6 am and finishing at 6pm. A total of 16 surveyors were employed over three days 
and two video cameras (although the second camera was deployed only the last day). Surveyors duties were to interview
the drivers, perform vehicle observations and operate the video cameras. The cameras were collecting data on the traffic outside the mall.
      
#### Overview of data collected
A total of **<span style='color:red'>1808 goods vehicles</span>** have been observed and **<span style='color:red'>347 drivers</span>** 
were interviewed, over three days of data collection activity.
                                                                            
#### Site description
* **Mall1 mall**: The mall is located in the north part of Singapore, at the intersection between Yishun Central 1 
and Yishun Central. In the vicinity of the mall there is the Yishun subway station and the Yishun Bus Interchange.
                                                 
   There are a total of **<span style='color:red'>170 stores</span>**, distributed over 3 floors overground (levels 01-03) and two 
floors underground (levels B1-B3). The combined lettable area is of 21800 squared meters. Among large retailers there is Cold Storage and POPULAR.

* **Service road**: Goods and passenger vehicles can access the mall from a 150 meters-long one-way two-lanes service road,
on the sides of which two cameras were deployed, one at the beginning of the road, one at the exit.
The road section analysed contains one traffic light with red clearance of 30 seconds.

* **Passenger car-park**: The passenger car-park is accessible at the end of the service road, there is only one entrance/exit. 
Each vehicle entering the carpark have to pay SG$ 1.20 for the first hour and SG$ 0.80 for every 
subsequent 15 minutes.

* **Loading bay**: The loading bay is accessible half-way though the service road and is located outside the mall.
**<span style='color:red'>It can hosts up to 6 goods vehicles</span>**. 
Access to the LB is **<span style='color:red'>free</span>**, on-site guards usually regulate the traffic. 
The stores can be accessed from the loading bay via a service lift.

* **Queue formation**: The queue for accessing the loading bay **<span style='color:red'>immediately spills over in the service road</span>**, 
and sometimes up to the main road (Yishun Central 1) when at least **<span style='color:red'>7 vehicles</span>** are in queue.

* **Street parking**: Illegal parking on the service road was occasionally observed 
along the sides of the service road as shown in the above map (green areas), for a total of approximately **<span style='color:red'>10 goods 
vehicles</span>** simultaneously.



"))) 
  ),
  column(4,
    br(),
    imageOutput("northp_overview")
  )  
                        
  ), # END of overview
               
tabPanel("Vehicle count",
         fluidRow(
           br(),
           column(3,
                  wellPanel(
                    radioButtons("northp_vehicle_count_visual", "Choose type of visualization:", 
                                 choices = c("Table","Percentage", "Barplot")),
                    selectInput("northp_vehicle_split", "Split by:", 
                                choices=c("No split"="none",
                                          "Interviewed vs. non-interviewed"="employer", 
                                          "Vehicle type"="vehicle_type", 
                                          "Refrigerated vs. non-rerigerated"="refrigerated",
                                          "Parking location"="park_location",
                                          "Number of workers"="no_workers"))
                  )    
           ),
           column(8, offset=1,
                  DT::dataTableOutput("northp_vehicle_table")
           )
         ) #END of fluidrow
), # END of vehicle count
                   
tabPanel("Delivery count",
         fluidRow(
           br(),
           column(3,
                  wellPanel(
                    radioButtons("northp_delivery_count_visual", "Choose type of visualization:", 
                                 choices = c("Table","Percentage", "Barplot")),
                    selectInput("northp_delivery_split", "Split by:", 
                                choices=c("Deliveries vs. pick-ups"="del_pick", 
                                          "Size of delivery"="del_size", 
                                          "Commodity type"="commodity_type",
                                          "Type of store deliverying to"="store_type"))
                  )    
           ),
           column(8, offset=1,
                  DT::dataTableOutput("northp_delivery_table")
           )
         ) #END of fluidrow
  )
) #END of tabsetpanel
                 
), ### END OF NORTHPOINT conditionalpanel



textOutput("data_collection_location"),
textOutput("clickme"),
tags$head(tags$style("#data_collection_location{color: white;}")),
tags$head(tags$style("#clickme{color: white;}"))

) #END of second row

),


############################################################################################################
## Tab 4: DATA VISUALIZATION
tabPanel("Visuals",
br(),
tabsetPanel(
  
tabPanel("Introduction", ################################
  br(),
  h3("Freight traffic at large retail establishments"),
  p("A simplified description of the delivery process at a large retail establishment is as follows. ..."),
  imageOutput("LBbay_flowchart"),
  br(),
  h3("Index list of visualizations"),
  p("...")
           
), # END of Intro  
  
  

tabPanel("System performance", ################################
         br(),
         fluidRow(
           column(4,
                  wellPanel(
                    checkboxInput("without_passby", "Eliminates vehicles passying by"),
                    checkboxGroupInput("park_location", "Show vehicles that parked...", 
                                       choices = c("...inside the loading bay"="LB",
                                                    "...inside the passenger carpark"="carpark", 
                                                   "...on the street"="street"))
                  )
           ),
           column(8,
                  dygraphOutput("step_plot")
           )
           
         )
), # END of System performance



  
tabPanel("Arrivals", ################################
  br(),
  fluidRow(
    column(3,
      wellPanel(
        checkboxGroupInput("input_date", "Choose date:", 
                           choices = c("Wednesday 24th June"="2015-06-24", 
                                       "Thursday 25th June"="2015-06-25", 
                                       "Friday 26th June"="2015-06-26"),
                           selected = "Wednesday 24th June"),
        sliderInput("input_interval", label="Choose time interval size:", value=50, min=10, max=90, step=10)
          )
    ),
    column(9,
           dygraphOutput("arrivals_plot")
           )
    
  )
), # END of Arrivals
  


tabPanel("Handling", ################################
  br(),
  fluidRow(
    column(3,
      wellPanel(
        selectInput("which_visualization_handling", "Select the visualization:", 
                    choices= c("Handling times distribution"="htime_distribution", 
                               "Handling times vs. size of delivery/pick-up"="htime_delsize",
                               "Handling time by arrival time"), 
                    selected="htime_distribution"),
        h4("Add filters:"),
        checkboxInput("onlygv_handling", "Include only goods vehicle"),
        checkboxInput("byparkloc", "Differentiate by park location"),
        conditionalPanel(
          condition = "input.byparkloc",
          checkboxGroupInput("park", "Park location:", c("Street"="street", "Loading bay"="LB", "Carpark"="carpark"))
        )
      )#END OF wellPanel
    ), #END of column
    column(9,
      conditionalPanel(
        condition="input.which_visualization_handling=='htime_distribution'",
        textOutput("nrowsfinal"),
        plotOutput("hist_htime")
        ),
      conditionalPanel(
        condition="input.which_visualization_handling=='htime_delsize'",
        #plotOutput("delsize_htime")
        "coming soon!"
      )
      )
    )
), # END of Handling
  

tabPanel("Queueing", ################################
  br(),
  fluidRow(
    column(4,
      wellPanel(
        checkboxInput("onlygv_queue", "Include only goods vehicle."),
        checkboxInput("onlyLB_queue", "Include only vehicles that parked in the loading bay.")
        )
      ),
      
    column(8,
        "main panel",
        plotOutput("hist_queue")
        )
      )
), # END of Queueing



tabPanel("Dwelling", ################################
  br(),
  fluidRow(
    column(4,
      wellPanel(
        checkboxInput("onlygv_dwell", "Include only goods vehicle.")
        )
      ),
      column(8,
          plotOutput("hist_dwell")
          )
        )
) # END of Dwelling

  
)#END of tabsetPanel under Visuals


           
) #end tabpanel Visuals

) #END of tabsetPanel()
) #END of column
), #END of fluidRow
fluidRow(
  column(10, offset=1,
  br(),
  br(),
  br(),
  hr(),
  column(2, offset = 4, h5(" *** DISCLAIMER ***"))
  )
)

)# END of fluidPage
)# END of shinyUI()


      